#!/bin/sh /etc/rc.common
START=99
USE_PROCD=1
start_service() {
    mkdir -p /etc/gogdns
    procd_open_instance
    procd_set_param command /etc/gogdns/gogdns
    procd_set_param chdir /etc/gogdns
    procd_set_param env GOGDNS_BASE_PATH=/etc/gogdns
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
stop_service() {
    killall gogdns
}
